@baseUrl = http://localhost:8080
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/account
Content-Type:  application/json

{
  "name": "Felipe Ferreira",
  "email": "teste3@gmail.com",
  "password": "123"
}

###

# @name authenticate
POST {{baseUrl}}/auth
Content-Type:  application/json

{
  "email": "teste@gmail.com",
  "password": "123"
}


###

# @name refresh
POST  {{baseUrl}}/refresh
Content-Type:  application/json

{
  "token": "549d8f8d-d669-4374-bdb2-546634537d56"
}

###

# @name create_category_point
POST {{baseUrl}}/category-point
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "text": "you completed a new task",
  "value": 10
}

###

# @name get_info
GET {{baseUrl}}/info
Authorization: Bearer {{authToken}}

###

# @name get_ranking
GET {{baseUrl}}/ranking
Authorization: Bearer {{authToken}}

###

# @name update_user
PATCH  {{baseUrl}}/user
Authorization: Bearer {{authToken}}

{
  "name": "Felipe Ferreira"
  //"email": teste@gmail.com
  //"avatar" : File
}

###

# @name create_journey
POST {{baseUrl}}/journey
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "title": "New Journey",
  "description": "A new journey enrolation that I can to be possible to fetch anything with inglish and aprouch that things that u can not see again and against but is that you are a nothing",
  "max_day": 21
}


###

# @name fetch_journeys
GET {{baseUrl}}/journeys?page=1
Content-Type:  application/json
Authorization: Bearer {{authToken}}


###

# @name create_task
POST {{baseUrl}}/task
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "title": "Teste",
  "content": "Conteúdo da task"
}

###

# @name create_classday
POST {{baseUrl}}/classday
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "journey_id": "cb6c21d0-19fc-4198-b2e7-ced770c83ce1"
}

###

# @name get_classDay
GET {{baseUrl}}/classday
Content-Type:  application/json
Authorization: Bearer {{authToken}}

###

# @name get_teacher
GET {{baseUrl}}/teacher
Content-Type:  application/json
Authorization: Bearer {{authToken}}



