@baseUrl = http://192.168.0.3:8080
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
OST {{baseUrl}}/account
Content-Type:  application/json

{
  "name": "Felipe Ferreira",
  "email": "teste5@gmail.com",
  "password": "1234"
}

###

# @name authenticate
POST {{baseUrl}}/auth
Content-Type:  application/json

{
  "email": "teste@gmail.com",
  "password": "123"
}

###

# @name create_category_point
POST {{baseUrl}}/category-point
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "text": "you completed a new task",
  "value": 10
}

###

# @name get_info
GET {{baseUrl}}/info
Authorization: Bearer {{authToken}}

###

# @name get_ranking
GET {{baseUrl}}/ranking
Authorization: Bearer {{authToken}}

###

# @name update_user
PATCH  {{baseUrl}}/user
Authorization: Bearer {{authToken}}

{
  "name": "Felipe Ferreira"
  //"email": teste@gmail.com
  //"avatar" : File
}


###

# @name create_task
POST {{baseUrl}}/task
Content-Type:  application/json
Authorization: Bearer {{authToken}}

{
  "title": "Teste",
  "content": "Conteúdo da task"
}