version: '3.8'

services:
  postgres:
    container_name: nest-speak-up
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSGRES_DB: nest-speak-up
      DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres